# Generated by Django 3.0.7 on 2020-06-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=256, verbose_name='Тип\\Вид оборудования')),
                ('name_e', models.CharField(max_length=256, verbose_name='Название оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудования',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название производителя')),
                ('country', models.CharField(max_length=40, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производителя',
            },
        ),
        migrations.CreateModel(
            name='TechnicalParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_rate', models.CharField(max_length=40, verbose_name='Затрата энергии в час')),
                ('useful_life', models.CharField(max_length=40, verbose_name='Период полезного использования в годах')),
                ('price', models.CharField(max_length=40, verbose_name='Оптовая цена за единицу')),
                ('norm_repair', models.CharField(max_length=40, verbose_name='Норма межремонтных пробегов')),
                ('downtime_rate', models.CharField(max_length=40, verbose_name='Норма простоев оборудования')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='disser.Equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Технические характеристики оборудования ',
                'verbose_name_plural': 'Технические характеристики оборудования ',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='disser.Manufacturer', verbose_name='Производитель'),
        ),
    ]
